### ISSUE TITLE
Registration issue

### ISSUE THREAD

**Issue by milioudi-asep** [QualiChain/fe#420]
Got an error from registration screen: "Your acount has been created", "Unexpected error" therefore we couldn't login.
 Additionally, I cannot Login by using the email I used for registration as recruiter: asep.qualichain@gmail.com.

**Comment by pzarafidis** [comment]
After several tests, we narrowed the problem down as a registration problem when we connected to http://qualichain.epu.ntua.gr/login from within ASEP network. Our network team further noticed that port 5004 was involved and as soon as it was "opened" the problem was resolved.
We think that should be discussed by the technical team if such a requirement (that 5004 port should be open) is acceptable for any end user (and should be included in any instructions to end users) or it should be corrected.

**Comment by mmilaprat** [comment]
we moved it to port 80
